### ISSUE TITLE
Special Characters in password

### ISSUE THREAD

**Issue by BluetriX** [schurig/ynab-bank-importer#40]
I have a "!" at the beginnung of my password so I am getting:

Traceback (most recent call last):
        8: from /usr/app/run.rb:9:in `<main>'
        7: from /usr/app/lib/settings.rb:8:in `all'
        6: from /usr/local/lib/ruby/2.5.0/psych.rb:497:in `load_file'
        5: from /usr/local/lib/ruby/2.5.0/psych.rb:497:in `open'
        4: from /usr/local/lib/ruby/2.5.0/psych.rb:498:in `block in load_file'
        3: from /usr/local/lib/ruby/2.5.0/psych.rb:263:in `load'
        2: from /usr/local/lib/ruby/2.5.0/psych.rb:350:in `parse'
        1: from /usr/local/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
/usr/local/lib/ruby/2.5.0/psych.rb:402:in `parse': (./config.yml): did not find expected tag URI while parsing a tag at line 11 column 15 (Psych::SyntaxError)

How do I escape my password?

**Comment by schurig** [comment]
Hi @BluetriX, can you try to put your password into quotes?

```yaml
accounts:
  - dumper: :fints
    iban: # iban of your account
    ynab_id: # last hash in the url when you click on the account in YNAB
    username: # online banking username / alias
    password: "!yourPasswordHere"
```

Let me know if it works
