### ISSUE TITLE
Undefined method map

### ISSUE THREAD

**Issue by BluetriX** [schurig/ynab-bank-importer#41]
C:\Users\erikb\docker>docker-compose pull importer && docker-compose run --rm importer
Pulling importer ... done
Traceback (most recent call last):
/usr/app/run.rb:9:in `<main>': undefined method `map' for nil:NilClass (NoMethodError)

**Comment by BluetriX** [comment]
Pherhaps this is a docker on windows bug. It does not matter if its n26 or fints

**Comment by schurig** [comment]
Hi @BluetriX, I think this issue might be related to a wrong configuration. The configuration inside the `config.yml` should look like this:

```yaml
---
ynab:
  access_token: # Your YNAB access token
  budget_id: # the first hash in the url when you open your budget
  cash_account_id:  # if set that it creates transactions
                            # to your cash account if withdrawal is detected
accounts:
  - dumper: :fints
    iban: "DE12345678945679"
    ynab_id: "123456-23456-23456-777777"
    username: "username"
    password: "your-password"
    fints_blz: "12345643"
    fints_endpoint: "https://endpoint-of-yourbank/to/hbic-fints"
  - dumper: :n26
    iban: "DE12345678945678"
    ynab_id: "123456-23456-23456-23456"
    username: "your-username"
    password: "your-password"
    skip_pending_transactions: false
```
