### ISSUE TITLE
Connection refused http.rb:939:in

### ISSUE THREAD

**Issue by hahaa24** [schurig/ynab-bank-importer#50]
I installed everything needed to run on an Ubuntu 18.04 LTS container.

I used this command for all the tools needed:
`sudo apt install git autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev ruby-all-dev libcurl4-openssl-dev ruby-bundler -y`

Then I installed Ruby and everything else using this set of commands:
`git clone https://github.com/rbenv/rbenv.git ~/.rbenv; echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc; echo 'eval "$(rbenv init -)"' >> ~/.bashrc;  source ~/.bashrc; type rbenv; git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build; rbenv install 2.5.0;`

Then I cloned the git files, did the bundle install and created this config:
```
---
ynab:
  access_token: "bc69ca9******"
  budget_id: "998*****"
  cash_account_id: # (optional)
accounts:
  - dumper: :fints
    iban: "DE28*****"
    ynab_id: "20*****"
    fints_endpoint: "banking-by7.s-fints-pt-by.de"
    fints_blz: "79****"
    username: "04******"
    password: "f*****"
```

**Comment by schurig** [comment]
Hi @hahaa24, could you give it an other try with the following endpoint?

`https://banking-by7.s-fints-pt-by.de/fints30`

**Comment by hahaa24** [comment]
That seems to be the solution, it loads a bit longer but then says `account must be formatted as a uuid` and this 60 times. Is this a known error?

**Comment by schurig** [comment]
It sounds a bit like either your `ynab_id` or `budget_id` is wrong. Do you mind double checking? In case it still happens, can you also post the stracktrace please?

**Comment by hahaa24** [comment]
I found the error within my `ynab_id` I put in something with numbers only I found at my budgets tab. What helped me to find the right id was this: https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/YNAB-Account-ID

Now everything is working just like magic. I think the installation guide is a bit too less detailed for complete amateurs like me. I would agree to make a more detailed guide on how to install your importer on a ubuntu 18.04, if you want to.
And thank you very much for the quick help.

**Comment by hahaa24** [comment]
Now I try to setup a second account in this config, but then I get an error. I probably only got the formatting wrong. The account is at the same bank and has the same login, only the IBAN differs. (And the `ynab_id` in the config.

The config:
```
---
ynab:
  access_token: "bc69ca9******"
  budget_id: "998******"
  cash_account_id: # (optional)
accounts:
  - dumper: :fints
    iban: "DE2879******"
    ynab_id: "ee3e6e******"
    fints_endpoint: "https://banking-by7.s-fints-pt-by.de/fints30"
    fints_blz: "79650000"
    username: "043*********"
    password: "f***"

  - dumper: :fints
    iban: "DE2879*******"
    ynab_id: "14ce3d******"
    fints_endpoint: "https://banking-by7.s-fints-pt-by.de/fints30"
    fints_blz: "79650000"
    username: "043*******"
    password: "f****"
```

And the error:
`Traceback (most recent call last):
	6: from run.rb:9:in `<main>'
	5: from run.rb:9:in `map'
	4: from run.rb:11:in `block in <main>'
	3: from /home/linux/ynab-bank-importer/lib/account.rb:18:in `fetch_transactions'
	2: from /home/linux/ynab-bank-importer/lib/dumper/fints.rb:22:in `fetch_transactions'
	1: from /var/lib/gems/2.5.0/gems/ruby_fints-0.0.3/lib/fints/client.rb:50:in `get_statement'
/var/lib/gems/2.5.0/gems/ruby_fints-0.0.3/lib/fints/client.rb:90:in `create_statement_message': undefined method `[]' for nil:NilClass (NoMethodError)
`
