### ISSUE TITLE
 `entry_date': undefined method `month'

### ISSUE THREAD

**Issue by yuvke** [schurig/ynab-bank-importer#52]
Hi,

I'm trying to run the script locally on Mac (directly in terminal, I have ruby installed).
I'm getting the following error:

``` bash
/Library/Ruby/Gems/2.3.0/gems/cmxl-0.2.2/lib/cmxl/fields/transaction.rb:63:in `entry_date': undefined method `month' for "190229":String (NoMethodError)
        from /Users/yuvalshaked/yuvdev/ynab-bank-importer/lib/dumper/fints.rb:34:in `date'
        from /Users/yuvalshaked/yuvdev/ynab-bank-importer/lib/dumper.rb:19:in `to_ynab_transaction'
        from /Users/yuvalshaked/yuvdev/ynab-bank-importer/lib/dumper/fints.rb:24:in `block in fetch_transactions'
        from /Users/yuvalshaked/yuvdev/ynab-bank-importer/lib/dumper/fints.rb:24:in `map'
        from /Users/yuvalshaked/yuvdev/ynab-bank-importer/lib/dumper/fints.rb:24:in `fetch_transactions'
        from /Users/yuvalshaked/yuvdev/ynab-bank-importer/lib/account.rb:18:in `fetch_transactions'
        from run.rb:11:in `block in <main>'
        from run.rb:9:in `map'
        from run.rb:9:in `<main>'
```

My config is:

``` yaml
ynab:
  access_token: "xxxxxxxxxxxxxxxxxxx919237484383ebe0" # Your YNAB access token
  budget_id: "xxxxxxxx-xxxx-xxxxx-xxxxxx-8c90ac86a0e0" # the first hash in the url when you open your budget
  cash_account_id: "xxxxxxxx-xxxxx-xxxxx-xxxxx-57c2e77ecdc9" # if set that it creates transactions
                            # to your cash account if withdrawal is detected
accounts:
  - dumper: :fints
    iban: "DE3210050000xxxxxxxxxxxx" # iban of your account
    ynab_id: "xxxxxxxx-xxxx-xxxx-xxxx-dada1c650246" # last hash in the url when you click on the account in YNAB
    username: "username" # online banking username / alias
    password: "password" # online banking PIN (NOT! the pin of your bank card!)
    fints_blz: "10050000" # Your bank's code / Bankleitzahl
    fints_endpoint: "https://banking-be3.s-fints-pt-be.de/fints30" # more info can be found here: https://github.com/schurig/ynab-bank-importer/wiki/FinTS---HBCI#fints_endpoint
  - dumper: :n26
    iban: # n26 iban
    ynab_id: # last hash in the url when you click on the account in YNAB
    username: # n26 username
    password: # n26 password
    skip_pending_transactions: false # default: false, only imports transactions when they're processed
    set_category: false # default: false, sets the N26 category name as category
```

Any idea what may be causing this?
