### ISSUE TITLE
FinTS::DialogError with ING-DiBa Account

### ISSUE THREAD

**Issue by kiliankoe** [schurig/ynab-bank-importer#64]
Hi!

I've been successfully using this for syncing an N26 account to my YNAB for a few months, thanks so much for that convenience ❤️ 

On trying to add an ING-DiBa account however I'm running into the following issue:

```
Traceback (most recent call last):
	7: from /usr/app/run.rb:9:in `<main>'
	6: from /usr/app/run.rb:9:in `map'
	5: from /usr/app/run.rb:11:in `block in <main>'
	4: from /usr/app/lib/account.rb:18:in `fetch_transactions'
	3: from /usr/app/lib/dumper/fints.rb:21:in `fetch_transactions'
	2: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/client.rb:19:in `get_sepa_accounts'
	1: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/dialog.rb:39:in `sync'
/usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/dialog.rb:83:in `send_msg': {"9800"=>"Der Dialog wurde abgebrochen.", "9010"=>"Ungültiger Signaturaufbau?: Fehler im Segmentaufbau."} (FinTS::DialogError)
```

I'm using the correct IBAN, FinTS Endpoint (https://fints.ing-diba.de/fints/), FinTS BLZ (50010517) and my username and password which I use to authenticate to ING-DiBa's online banking. Everything's quoted as well to be parsed as a string from the yaml config. 

Any idea what could be going wrong here?

Thanks!

**Comment by schurig** [comment]
Hi @kiliankoe, I'm glad to hear that it worked well for you so far :)

For me it works with the following configuration:

```yaml
- dumper: :fints
  iban: 'DE5555555555555555555'
  ynab_id: '347834dsf-sdf3243-dffdghre324'
  ynab_name: 'Eingang: ING'
  username: '12345678910' # my login number that I also use for the browser-login
  password: 'mypassword'
  fints_endpoint: 'https://fints.ing.de/fints/' # https://fints.ing-diba.de/fints/ also works
  fints_blz: '50010517'
```

The IBAN is only used to get the statements (transactions) from the correct account, so it's not used for the authentication. The only 4 factors for the auth to work are: `fints_blz`, `password`, `username`, `fints_endpoint`: https://github.com/schurig/ynab-bank-importer/blob/master/lib/dumper/fints.rb#L19

So the only advice I could give right now is to double check your credentials. I hope for a mistake in them, otherwise I don't know how to resolve the issue 🤞
