### ISSUE TITLE
Problem with Sparkasse and FinTS

### ISSUE THREAD

**Issue by lukkigi** [schurig/ynab-bank-importer#75]
Hello,

first of all: amazing project! Been using it for months now with my ING account.

I ran into some troubles with a Sparkasse bank account though. 

```
accounts:
  - dumper: :fints
    iban: 'DE543305000xxxxxx'
    ynab_id: 'xxxxx'
    ynab_name: 'Sparkasse'
    username: '15xxxxxxxx' # my login number that I also use for the browser-login
    password: 'xxxxxxx'
    fints_endpoint: 'https://banking-rl3.s-fints-pt-rl.de/fints30'
    fints_blz: '33050000'
```

```
[1mTraceback[m (most recent call last): 
7: from /usr/app/run.rb:9:in `<main>' 
6: from /usr/app/run.rb:9:in `map' 
5: from /usr/app/run.rb:11:in `block in <main>' 
4: from /usr/app/lib/account.rb:18:in `fetch_transactions' 
3: from /usr/app/lib/dumper/fints.rb:21:in `fetch_transactions' 
2: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/client.rb:19:in `get_sepa_accounts' 
1: from /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/dialog.rb:39:in `sync' /usr/local/bundle/gems/ruby_fints-0.0.3/lib/fints/dialog.rb:83:in `send_msg': [1m{"9050"=>"Die Nachricht enthält Fehler.", "9800"=>"Dialog abgebrochen", "9010"=>"Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet."} ([1;4mFinTS::DialogError[m[1m)[m
```

I've double checked the crendentials and they seem to be correct. Can you spot anything I'm doing wrong?
